volumes:
  nats-data:
  mongo-data:
  thumbs:

networks:
  internal:

services:
  nats:
    image: nats
    restart: always
    command:
      - "--js"
      - "--sd=/data"
    networks:
      - internal
    ports:
      - 4222:4222 # for debugging
      - 8222:8222 # for debugging
    volumes:
      - nats-data:/data

  mongodb: 
    image: mongo:8
    restart: always
    networks:
      - internal
    ports:
      - 27017:27017 # for debugging
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - internal
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
  
  api-gateway:
    image: seraph
    restart: always
    command: 
      - api-gateway
    depends_on:
      - nats
      - mongodb
    networks:
      - internal
    ports:
      - 8080:8080
    environment:
      GIN_MODE: debug
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_MONGO_URL: mongodb://mongodb:27017/
      SERAPH_AUTH_ENABLED: false
      SERAPH_AUTH_CONFIGURL: https://localhost:8180/realms/seraph
      SERAPH_AUTH_REDIRECTURL: http://localhost:8080/auth/callback
      SERAPH_AUTH_CLIENTID: seraph
      SERAPH_LOG_LEVEL: debug

  file-indexer:
    image: seraph
    restart: always
    command: 
      - file-indexer
    depends_on:
      - nats
      - mongodb
    networks:
      - internal
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_MONGO_URL: mongodb://mongodb:27017/
      SERAPH_LOG_LEVEL: debug

  thumbnailer:
    image: seraph
    restart: always
    command: 
      - thumbnailer
    depends_on:
      - nats
      - file-provider-thumbs
    networks:
      - internal
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_THUMBNAILER_PROVIDERID: thumbs
      SERAPH_THUMBNAILER_PARALLEL: 8
      SERAPH_LOG_LEVEL: debug

  shares:
    image: seraph
    restart: always
    command: 
      - shares
    depends_on:
      - nats
      - mongodb
    networks:
      - internal
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_MONGO_URL: mongodb://mongodb:27017/
      SERAPH_LOG_LEVEL: debug

  spaces:
    image: seraph
    restart: always
    command: 
      - spaces
    depends_on:
      - nats
      - mongodb
    networks:
      - internal
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_MONGO_URL: mongodb://mongodb:27017/
      SERAPH_LOG_LEVEL: debug

  jobs:
    image: seraph
    restart: always
    command: 
      - jobs
    depends_on:
      - nats
    networks:
      - internal
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_LOG_LEVEL: debug

  file-provider-thumbs:
    image: seraph
    restart: always
    command: 
      - file-provider-dir
    depends_on:
      - nats
    networks:
      - internal
    volumes:
      - thumbs:/data
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_FILEPROVIDER_ID: thumbs
      SERAPH_FILEPROVIDER_DIR: /data
    
  file-provider-dir:
    image: seraph
    restart: always
    command: 
      - file-provider-dir
    depends_on:
      - nats
    networks:
      - internal
    volumes:
      - /home/vortex/loeschen/test:/data
    environment:
      SERAPH_NATS_URL: nats://nats:4222
      SERAPH_FILEPROVIDER_ID: dirtest
      SERAPH_FILEPROVIDER_DIR: /data
