package thumbnailer

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// ThumbnailRequest is a generated struct.
type ThumbnailRequest struct {
	Path   string `avro:"path"`
	Width  int    `avro:"width"`
	Height int    `avro:"height"`
	Exact  bool   `avro:"exact"`
}

var schemaThumbnailRequest = avro.MustParse(`{"name":"seraph.thumbnailer.ThumbnailRequest","type":"record","fields":[{"name":"path","type":"string"},{"name":"width","type":"int"},{"name":"height","type":"int"},{"name":"exact","type":"boolean"}]}`)

// Schema returns the schema for ThumbnailRequest.
func (o *ThumbnailRequest) Schema() avro.Schema {
	return schemaThumbnailRequest
}

// Unmarshal decodes b into the receiver.
func (o *ThumbnailRequest) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *ThumbnailRequest) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

// ThumbnailResponse is a generated struct.
type ThumbnailResponse struct {
	Error string `avro:"error"`
	Path  string `avro:"path"`
}

var schemaThumbnailResponse = avro.MustParse(`{"name":"seraph.thumbnailer.ThumbnailResponse","type":"record","fields":[{"name":"error","type":"string"},{"name":"path","type":"string"}]}`)

// Schema returns the schema for ThumbnailResponse.
func (o *ThumbnailResponse) Schema() avro.Schema {
	return schemaThumbnailResponse
}

// Unmarshal decodes b into the receiver.
func (o *ThumbnailResponse) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *ThumbnailResponse) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
