package events

// Code generated by avro/gen. DO NOT EDIT.

// Event is a generated struct.
type Event struct {
	ID      string `avro:"id"`
	Version int    `avro:"version"`
}

// FileProviderEvent is a generated struct.
type FileProviderEvent struct {
	ProviderID string `avro:"providerId"`
}

// FileInfoEvent is a generated struct.
type FileInfoEvent struct {
	Event             Event             `avro:"event"`
	FileProviderEvent FileProviderEvent `avro:"fileProviderEvent"`
	Readdir           string            `avro:"readdir"`
	Last              bool              `avro:"last"`
	Name              string            `avro:"name"`
	Size              int64             `avro:"size"`
	Mode              int64             `avro:"mode"`
	ModTime           int64             `avro:"modTime"`
	IsDir             bool              `avro:"isDir"`
}
