package events

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Event is a generated struct.
type Event struct {
	ID      string `avro:"id" json:"id"`
	Version int    `avro:"version" json:"version"`
}

var schemaEvent = avro.MustParse(`{"name":"seraph.events.Event","type":"record","fields":[{"name":"id","type":"string"},{"name":"version","type":"int"}]}`)

// Schema returns the schema for Event.
func (o *Event) Schema() avro.Schema {
	return schemaEvent
}

// Unmarshal decodes b into the receiver.
func (o *Event) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Event) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

// ReadDir is a generated struct.
type ReadDir struct {
	Readdir string `avro:"readdir" json:"readdir"`
	Index   int64  `avro:"index" json:"index"`
	Total   int64  `avro:"total" json:"total"`
}

var schemaReadDir = avro.MustParse(`{"name":"seraph.events.ReadDir","type":"record","fields":[{"name":"readdir","type":"string"},{"name":"index","type":"long"},{"name":"total","type":"long"}]}`)

// Schema returns the schema for ReadDir.
func (o *ReadDir) Schema() avro.Schema {
	return schemaReadDir
}

// Unmarshal decodes b into the receiver.
func (o *ReadDir) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *ReadDir) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

// FileInfoEvent is a generated struct.
type FileInfoEvent struct {
	Event      Event    `avro:"event" json:"event"`
	ProviderID string   `avro:"providerId" json:"providerId"`
	Readdir    *ReadDir `avro:"readdir" json:"readdir"`
	Path       string   `avro:"path" json:"path"`
	Size       int64    `avro:"size" json:"size"`
	Mode       int64    `avro:"mode" json:"mode"`
	ModTime    int64    `avro:"modTime" json:"modTime"`
	IsDir      bool     `avro:"isDir" json:"isDir"`
}

var schemaFileInfoEvent = avro.MustParse(`{"name":"seraph.events.FileInfoEvent","type":"record","fields":[{"name":"event","type":"seraph.events.Event"},{"name":"providerId","type":"string"},{"name":"readdir","type":["seraph.events.ReadDir","null"]},{"name":"path","type":"string"},{"name":"size","type":"long"},{"name":"mode","type":"long"},{"name":"modTime","type":"long"},{"name":"isDir","type":"boolean"}]}`)

// Schema returns the schema for FileInfoEvent.
func (o *FileInfoEvent) Schema() avro.Schema {
	return schemaFileInfoEvent
}

// Unmarshal decodes b into the receiver.
func (o *FileInfoEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *FileInfoEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

// FileChangedEvent is a generated struct.
type FileChangedEvent struct {
	Event      Event  `avro:"event" json:"event"`
	FileID     string `avro:"fileId" json:"fileId"`
	ProviderID string `avro:"providerId" json:"providerId"`
	Change     string `avro:"change" json:"change"`
	Path       string `avro:"path" json:"path"`
	Size       int64  `avro:"size" json:"size"`
	Mode       int64  `avro:"mode" json:"mode"`
	ModTime    int64  `avro:"modTime" json:"modTime"`
	IsDir      bool   `avro:"isDir" json:"isDir"`
	Mime       string `avro:"mime" json:"mime"`
}

var schemaFileChangedEvent = avro.MustParse(`{"name":"seraph.events.FileChangedEvent","type":"record","fields":[{"name":"event","type":"seraph.events.Event"},{"name":"fileId","type":"string"},{"name":"providerId","type":"string"},{"name":"change","type":"string"},{"name":"path","type":"string"},{"name":"size","type":"long"},{"name":"mode","type":"long"},{"name":"modTime","type":"long"},{"name":"isDir","type":"boolean"},{"name":"mime","type":"string"}]}`)

// Schema returns the schema for FileChangedEvent.
func (o *FileChangedEvent) Schema() avro.Schema {
	return schemaFileChangedEvent
}

// Unmarshal decodes b into the receiver.
func (o *FileChangedEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *FileChangedEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

// JobEvent is a generated struct.
type JobEvent struct {
	Event         Event             `avro:"event" json:"event"`
	Key           string            `avro:"key" json:"key"`
	Description   string            `avro:"description" json:"description"`
	StatusMessage string            `avro:"statusMessage" json:"statusMessage"`
	Properties    map[string]string `avro:"properties" json:"properties"`
}

var schemaJobEvent = avro.MustParse(`{"name":"seraph.events.JobEvent","type":"record","fields":[{"name":"event","type":"seraph.events.Event"},{"name":"key","type":"string"},{"name":"description","type":"string"},{"name":"statusMessage","type":"string"},{"name":"properties","type":{"type":"map","values":"string"}}]}`)

// Schema returns the schema for JobEvent.
func (o *JobEvent) Schema() avro.Schema {
	return schemaJobEvent
}

// Unmarshal decodes b into the receiver.
func (o *JobEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *JobEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
